application: shop-guru
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /receive
  script: launcher/appengine_launcher.py

libraries:
- name: MySQLdb
  version: latest